from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

# Sheet 1: Monthly Data
ws1 = wb.active
ws1.title = "MonthlyData"

# Headers
headers1 = ['Month', 'TotalEngagement', 'ReportsGenerated', 'IssuesRaised']
ws1.append(headers1)

# Style headers
for col in range(1, len(headers1) + 1):
    cell = ws1.cell(1, col)
    cell.font = Font(bold=True, color='FFFFFF')
    cell.fill = PatternFill(start_color='2C3E50', end_color='2C3E50', fill_type='solid')
    cell.alignment = Alignment(horizontal='center', vertical='center')

# Sample data
monthly_data = [
    ['Oct', 520, 110, 8],
    ['Nov', 580, 125, 10],
    ['Dec', 630, 136, 11],
    ['Jan', 680, 152, 14]
]

for row in monthly_data:
    ws1.append(row)

# Format columns
ws1.column_dimensions['A'].width = 12
ws1.column_dimensions['B'].width = 18
ws1.column_dimensions['C'].width = 18
ws1.column_dimensions['D'].width = 15

# Sheet 2: Division Data
ws2 = wb.create_sheet("DivisionData")

headers2 = ['ConcreteRepairs', 'MembraneRoofing', 'Facade', 'Tanking', 'OldSansom']
ws2.append(headers2)

# Style headers
for col in range(1, len(headers2) + 1):
    cell = ws2.cell(1, col)
    cell.font = Font(bold=True, color='FFFFFF')
    cell.fill = PatternFill(start_color='2C3E50', end_color='2C3E50', fill_type='solid')
    cell.alignment = Alignment(horizontal='center', vertical='center')

# Sample trend data (4 months for each division)
division_data = [
    [95, 70, 78, 45, 232],
    [100, 75, 85, 48, 272],
    [108, 83, 89, 55, 295],
    [124, 87, 82, 67, 320]
]

for row in division_data:
    ws2.append(row)

# Format columns
for col in range(1, len(headers2) + 1):
    ws2.column_dimensions[get_column_letter(col)].width = 16

# Sheet 3: Current Month Summary
ws3 = wb.create_sheet("CurrentMonth")

headers3 = ['Division', 'TotalEngagement', 'Pass', 'Fail', 'NA', 'Reports', 'Issues']
ws3.append(headers3)

# Style headers
for col in range(1, len(headers3) + 1):
    cell = ws3.cell(1, col)
    cell.font = Font(bold=True, color='FFFFFF')
    cell.fill = PatternFill(start_color='2C3E50', end_color='2C3E50', fill_type='solid')
    cell.alignment = Alignment(horizontal='center', vertical='center')

# Sample current month data
current_month_data = [
    ['Concrete Repairs', 124, 83, 2, 4, 28, 2],
    ['Membrane Roofing', 87, 50, 2, 11, 19, 3],
    ['Facade', 82, 70, 1, 9, 18, 2],
    ['Tanking', 67, 26, 0, 1, 15, 0],
    ['Old Sansom', 320, 241, 10, 18, 72, 7]
]

for row in current_month_data:
    ws3.append(row)

# Format columns
ws3.column_dimensions['A'].width = 18
for col in range(2, len(headers3) + 1):
    ws3.column_dimensions[get_column_letter(col)].width = 16

# Add instructions sheet
ws_instructions = wb.create_sheet("Instructions", 0)
ws_instructions.column_dimensions['A'].width = 80

instructions = [
    ["QA DASHBOARD DATA TEMPLATE - INSTRUCTIONS"],
    [""],
    ["This Excel file contains the data that powers your QA Director Dashboard."],
    [""],
    ["HOW TO UPDATE THE DASHBOARD:"],
    ["1. Edit the data in the three data sheets (MonthlyData, DivisionData, CurrentMonth)"],
    ["2. Save this Excel file"],
    ["3. Upload it to your Render deployment (see deployment instructions)"],
    ["4. The dashboard will automatically refresh with your new data"],
    [""],
    ["SHEET DESCRIPTIONS:"],
    [""],
    ["MonthlyData Sheet:"],
    ["- Contains trend data across the last 4 months"],
    ["- Month: Short month name (e.g., Oct, Nov, Dec, Jan)"],
    ["- TotalEngagement: Total QA engagements for that month"],
    ["- ReportsGenerated: Number of reports created"],
    ["- IssuesRaised: Number of issues logged"],
    [""],
    ["DivisionData Sheet:"],
    ["- Contains engagement trends for each division over 4 months"],
    ["- Each column represents a division"],
    ["- Each row represents a month (matching MonthlyData months)"],
    ["- Values should be the engagement count for that division in that month"],
    [""],
    ["CurrentMonth Sheet:"],
    ["- Contains detailed breakdown for the CURRENT (most recent) month"],
    ["- Division: Division name (must match exactly)"],
    ["- TotalEngagement: Total engagements for this division this month"],
    ["- Pass: Number of passed QA checks"],
    ["- Fail: Number of failed QA checks"],
    ["- NA: Number of N/A QA checks"],
    ["- Reports: Number of reports generated by this division"],
    ["- Issues: Number of issues raised by this division"],
    [""],
    ["IMPORTANT NOTES:"],
    ["- Do NOT change the column headers or sheet names"],
    ["- Division names in CurrentMonth must match the column names in DivisionData"],
    ["- Keep the same number of months (4) in MonthlyData and DivisionData"],
    ["- The last row in DivisionData should match the TotalEngagement in CurrentMonth"],
    ["- All numbers should be whole numbers (integers)"],
    [""],
    ["If you need to add more months:"],
    ["- Add new rows to MonthlyData"],
    ["- Add new rows to DivisionData (keep columns aligned)"],
    ["- Make sure the months match across both sheets"]
]

for i, row in enumerate(instructions, 1):
    cell = ws_instructions.cell(i, 1)
    cell.value = row[0]
    if i == 1:
        cell.font = Font(bold=True, size=14, color='FFFFFF')
        cell.fill = PatternFill(start_color='2980B9', end_color='2980B9', fill_type='solid')
    elif "HOW TO UPDATE" in row[0] or "SHEET DESCRIPTIONS" in row[0] or "IMPORTANT NOTES" in row[0]:
        cell.font = Font(bold=True, size=12)
    elif row[0].endswith(":") and len(row[0]) < 30:
        cell.font = Font(bold=True)

wb.save('/home/claude/qa-dashboard/data/qa_dashboard_data.xlsx')
print("Excel template created successfully!")
